services:
  game-engine:
    build:
      context: ./game-engine
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./game-engine:/usr/src/game-engine
    command: cargo watch -x run
    environment:
      - RUST_LOG=debug